### ISSUE TITLE
Does not compile on systems with case sensitive filenames

### ISSUE THREAD

**Issue by eku** [funnypolynomial/FlipClock#1]
Thanks for making the project available on GitHub.

I'm trying to compile the project on Linux with case sensitive filenames and it fails to compile.

```
fatal error: arduino.h: No such file or directory

... and others

It's there as .platformio/packages/framework-arduino-avr/cores/arduino/Arduino.h
```

Would you please adjust the includes according to the actual spelling of the files. Thank you.

**Comment by funnypolynomial** [comment]
Done by inspection, seemed to just be a few "arduino.h"s, made them all <Arduino.h>
